// policy/privacy_policy.md 의 내용을 lib/privacy-text.generated.ts 로 복사한다.
// Metro 가 .md 파일을 직접 require 하지 못하므로 빌드 시점에 TS 상수로 변환한다.
// dev/start/build 직전에 자동 실행되도록 package.json 의 prestart/prebuild 에 연결.

import fs from "node:fs";
import path from "node:path";
import url from "node:url";

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..", "..", "..");
const src = path.join(repoRoot, "policy", "privacy_policy.md");
const dst = path.resolve(__dirname, "..", "lib", "privacy-text.generated.ts");

const md = fs.readFileSync(src, "utf8");
const out = `// AUTO-GENERATED from policy/privacy_policy.md — do not edit by hand.
// Re-generated by scripts/copy-privacy.mjs on prestart/prebuild.

export const PRIVACY_POLICY_MD = ${JSON.stringify(md)};
`;
fs.writeFileSync(dst, out, "utf8");
console.log(`[copy-privacy] wrote ${path.relative(repoRoot, dst)} (${md.length} chars)`);
